### ISSUE TITLE
About delay curves baselines

### ISSUE THREAD

**Issue by Allbarabin** [HelmchenLabSoftware/Centripetal_propagation_astrocytes#2]
Hello, I have a question. I used your code to run the Full FOV delay map, as showed in Fig. 6c, and obtained delay curves for different times, but their baselines are significantly different, gradually increasing from -3 to +3. I would like to ask if you have done any normalized processing?

**Comment by PTRRupprecht** [comment]
Hi @Allbarabin ,

To make sure that I fully understand your question, I believe that you first used the code of this repository to generate the full FOV delay map. From this delay map, you generated the delay bin masks as in [Fig. 6b](https://www.nature.com/articles/s41593-024-01612-8#Fig6), which you then used - with your own code - to extract the delay time traces as shown in Fig. 6c in the paper. Then you get a result similar to Fig. 6c, but the baseline is larger for more positive delays.

For most expression strategies, the baseline at the soma of astrocytes is higher compared to the gliapil, therefore one would expect higher baseline for those compartments; those compartments also exhibit typically more positive delays. Therefore, this is consistent with your finding.

In my analysis in Fig. 6c, I used a normalization using simple "dF/F" processing. This is a standard procedure that has been developed for neuronal calcium imaging 30 years ago. Basically, you take the baseline F_0 (which is the minimum value of the trace, or a lower percentile value of the trace; there is no binding convention and everybody just does what works for them) and compute dF/F = (F(t) - F_0)/F_0, with the raw fluorescence trace F(t). It is relevant to have properly scaled raw inputs with no PMT offset error. Using this procedure, you will probably get similar traces to Fig. 6c, with the baseline being normalized, and the resulting dF/F in %.

In theory, it would also be possible to simply z-score the traces instead of computing dF/F. In both cases (using z-scoring or dF/F), my goal would be to bring traces from different time bins to a similar scale, such that they can be more easily compared by eye.

I hope this helps already. If not, let me know!

Best,
Peter

**Comment by Allbarabin** [comment]
> Hi @Allbarabin ,
> 
> To make sure that I fully understand your question, I believe that you first used the code of this repository to generate the full FOV delay map. From this delay map, you generated the delay bin masks as in [Fig. 6b](https://www.nature.com/articles/s41593-024-01612-8#Fig6), which you then used - with your own code - to extract the delay time traces as shown in Fig. 6c in the paper. Then you get a result similar to Fig. 6c, but the baseline is larger for more positive delays.
> 
> For most expression strategies, the baseline at the soma of astrocytes is higher compared to the gliapil, therefore one would expect higher baseline for those compartments; those compartments also exhibit typically more positive delays. Therefore, this is consistent with your finding.
> 
> In my analysis in Fig. 6c, I used a normalization using simple "dF/F" processing. This is a standard procedure that has been developed for neuronal calcium imaging 30 years ago. Basically, you take the baseline F_0 (which is the minimum value of the trace, or a lower percentile value of the trace; there is no binding convention and everybody just does what works for them) and compute dF/F = (F(t) - F_0)/F_0, with the raw fluorescence trace F(t). It is relevant to have properly scaled raw inputs with no PMT offset error. Using this procedure, you will probably get similar traces to Fig. 6c, with the baseline being normalized, and the resulting dF/F in %.
> 
> In theory, it would also be possible to simply z-score the traces instead of computing dF/F. In both cases (using z-scoring or dF/F), my goal would be to bring traces from different time bins to a similar scale, such that they can be more easily compared by eye.
> 
> I hope this helps already. If not, let me know!
> 
> Best, Peter

Tanks very much.
